export const STORE_PLATFORM_IDS = [
  'shopify',
  'woocommerce',
  'wix',
  'bigcommerce',
  'magento',
  'squarespace',
  'prestashop',
  'opencart',
  'square',
];

const API_FIELD_SHOPIFY = [
  {
    name: 'admin_access_token',
    label: 'Admin API access token',
    type: 'password',
    placeholder: 'shpat_...',
  },
];

const API_FIELD_WOOCOMMERCE = [
  {
    name: 'consumer_key',
    label: 'Consumer key',
    type: 'password',
    placeholder: 'ck_...',
  },
  {
    name: 'consumer_secret',
    label: 'Consumer secret',
    type: 'password',
    placeholder: 'cs_...',
  },
];

export const STORE_PLATFORMS = [
  {
    id: 'shopify',
    label: 'Shopify',
    logoSlug: 'shopify',
    brandColor: '7AB55C',
    summary: 'Connect your Shopify storefront to scan product pages and optionally push optimized SEO content with one click.',
    urlPlaceholder: 'https://your-store.myshopify.com',
    urlHelp: 'Use your public storefront URL. Custom domains work once the store is live.',
    passwordHelp: 'Password-protected development stores need the visitor password from Online Store → Preferences.',
    supportsApiPush: true,
    supportsOAuth: true,
    docsUrl: 'https://help.shopify.com/en/manual/online-store/setting-up',
    connectSteps: [
      'Open your Shopify admin and confirm products are published to the Online Store channel.',
      'Copy your live storefront URL (myshopify.com or custom domain).',
      'If the store is password-protected, copy the visitor password from Online Store → Preferences.',
      'Paste the URL below and connect — we scan your public sitemap for product pages.',
      'After connecting, use Guided API setup for one-click push or Shopify OAuth sign-in.',
    ],
    apiSteps: [
      'Log in to your Shopify admin.',
      'Go to Settings → Apps and sales channels.',
      'Click Develop apps, then Create an app.',
      'Open Configuration → Admin API integration.',
      'Enable scopes: read_products and write_products.',
      'Install the app, then reveal the Admin API access token.',
      'Paste the token below. It usually starts with shpat_.',
    ],
    apiSummary: 'Create a custom app in Shopify admin and paste the Admin API access token.',
    apiDocsUrl: 'https://help.shopify.com/en/manual/apps/app-types/custom-apps',
    apiFields: API_FIELD_SHOPIFY,
    publishSteps: [
      'Open Shopify admin → Products.',
      'Edit the product you want to update.',
      'Copy the optimized title, description, and SEO fields from AI Commerce Suite.',
      'Save the product.',
    ],
  },
  {
    id: 'woocommerce',
    label: 'WooCommerce',
    logoSlug: 'woocommerce',
    brandColor: '96588A',
    summary: 'Connect your WordPress/WooCommerce store to audit live product pages from your public sitemap.',
    urlPlaceholder: 'https://yourstore.com',
    urlHelp: 'Enter your WordPress site homepage URL where WooCommerce is installed.',
    passwordHelp: 'Only needed if the entire site is behind HTTP auth or a maintenance lock.',
    supportsApiPush: false,
    supportsOAuth: false,
    docsUrl: 'https://woocommerce.com/document/woocommerce-rest-api/',
    connectSteps: [
      'Make sure WooCommerce is installed and products are published.',
      'Confirm your site exposes a sitemap (Yoast, Rank Math, or /wp-sitemap.xml).',
      'Copy your store homepage URL.',
      'Paste it below — we discover product URLs from your public sitemap.',
      'Optional: add REST API keys in Guided setup to prepare for future integrations.',
    ],
    apiSteps: [
      'Log in to WordPress admin.',
      'Go to WooCommerce → Settings → Advanced → REST API.',
      'Click Add key.',
      'Set permissions to Read/Write and generate the key.',
      'Copy the Consumer key and Consumer secret.',
      'Paste both values in Guided API setup.',
    ],
    apiSummary: 'Generate REST API keys in WooCommerce for verified store access.',
    apiDocsUrl: 'https://woocommerce.com/document/woocommerce-rest-api/',
    apiFields: API_FIELD_WOOCOMMERCE,
    publishSteps: [
      'Open WordPress admin → Products.',
      'Edit the product you want to update.',
      'Paste optimized title, description, and SEO fields.',
      'Update the product.',
    ],
  },
  {
    id: 'wix',
    label: 'Wix eCommerce',
    logoSlug: 'wix',
    brandColor: '0C6EFC',
    summary: 'Connect your Wix online store to scan published product pages for live SEO scores.',
    urlPlaceholder: 'https://www.yoursite.wixsite.com/mystore',
    urlHelp: 'Use your published Wix site URL (wixsite.com subdomain or connected custom domain).',
    passwordHelp: 'Enter the site password only if visitors must enter a password to view the store.',
    supportsApiPush: false,
    supportsOAuth: false,
    docsUrl: 'https://support.wix.com/en/article/about-your-sites-sitemap',
    connectSteps: [
      'Publish your Wix store and ensure products are visible on the live site.',
      'Open your live storefront in a browser and copy the homepage URL.',
      'In Wix, check SEO settings if product URLs use clean slugs.',
      'Paste the URL below — we read your public sitemap and product pages.',
      'Use export or copy from AI Commerce Suite to update products in Wix manually.',
    ],
    publishSteps: [
      'Open Wix dashboard → Store Products.',
      'Edit the product.',
      'Paste optimized content into title, description, and SEO settings.',
      'Publish changes.',
    ],
  },
  {
    id: 'bigcommerce',
    label: 'BigCommerce',
    logoSlug: 'bigcommerce',
    brandColor: '1A1A1A',
    summary: 'Connect your BigCommerce storefront to audit product SEO from live public pages.',
    urlPlaceholder: 'https://yourstore.com',
    urlHelp: 'Use your live storefront URL (custom domain or *.mybigcommerce.com).',
    passwordHelp: 'Required only if the storefront is behind a pre-launch or staging password.',
    supportsApiPush: false,
    supportsOAuth: false,
    docsUrl: 'https://support.bigcommerce.com/s/article/Sitemap',
    connectSteps: [
      'Confirm products are available on your live storefront.',
      'Copy your store\'s public homepage URL.',
      'BigCommerce sitemaps are usually at /xmlsitemap.php or linked in robots.txt.',
      'Paste the URL below to start the SEO scan.',
      'Export optimized content and paste into BigCommerce product editor.',
    ],
    publishSteps: [
      'Open BigCommerce → Products → View.',
      'Edit the product.',
      'Update name, description, and SEO fields from your export.',
      'Save the product.',
    ],
  },
  {
    id: 'magento',
    label: 'Magento (Adobe Commerce)',
    logoSlug: 'magento',
    brandColor: 'F26322',
    summary: 'Connect your Magento / Adobe Commerce store to scan public catalog pages.',
    urlPlaceholder: 'https://yourstore.com',
    urlHelp: 'Enter your live storefront base URL (not the admin /admin path).',
    passwordHelp: 'Use if the storefront is in maintenance mode with a shared visitor password.',
    supportsApiPush: false,
    supportsOAuth: false,
    docsUrl: 'https://experienceleague.adobe.com/docs/commerce-admin/marketing/seo/sitemap-xml.html',
    connectSteps: [
      'Ensure products are enabled and visible in the default store view.',
      'Verify your XML sitemap is enabled in Marketing → SEO & Search → Site Map.',
      'Copy your storefront homepage URL.',
      'Paste it below — we crawl your sitemap for product URLs.',
      'Use CSV export from AI Commerce Suite for bulk catalog updates in Magento.',
    ],
    publishSteps: [
      'Open Magento admin → Catalog → Products.',
      'Edit the product.',
      'Paste optimized content into name, description, and meta fields.',
      'Save the product.',
    ],
  },
  {
    id: 'squarespace',
    label: 'Squarespace',
    logoSlug: 'squarespace',
    brandColor: '000000',
    summary: 'Connect your Squarespace Commerce site to review live product page SEO.',
    urlPlaceholder: 'https://www.yourstore.com',
    urlHelp: 'Use your published Squarespace domain (custom domain or *.squarespace.com).',
    passwordHelp: 'Only if the site is still under a site-wide password before launch.',
    supportsApiPush: false,
    supportsOAuth: false,
    docsUrl: 'https://support.squarespace.com/hc/en-us/articles/206543167',
    connectSteps: [
      'Publish your site and confirm store products are live.',
      'Copy your homepage URL from the live site.',
      'Squarespace exposes a sitemap at /sitemap.xml on most plans.',
      'Paste the URL below to scan product pages (100 per batch).',
      'Copy optimized fields into Squarespace product pages manually.',
    ],
    publishSteps: [
      'Open Squarespace → Commerce → Products.',
      'Edit the product.',
      'Update title, description, and SEO description.',
      'Save.',
    ],
  },
  {
    id: 'prestashop',
    label: 'PrestaShop',
    logoSlug: 'prestashop',
    brandColor: 'DF0067',
    summary: 'Connect your PrestaShop store to audit product pages from your public catalog.',
    urlPlaceholder: 'https://yourstore.com',
    urlHelp: 'Enter your shop front URL (PrestaShop root, not /admin).',
    passwordHelp: 'Only if the shop front is restricted with a maintenance or HTTP password.',
    supportsApiPush: false,
    supportsOAuth: false,
    docsUrl: 'https://docs.prestashop-project.org/',
    connectSteps: [
      'Ensure products are active and indexed in your catalog.',
      'Enable the sitemap in Shop parameters → Traffic & SEO if available.',
      'Copy your store\'s public homepage URL.',
      'Paste it below — we discover product URLs from your sitemap.',
      'Use export files to update products in PrestaShop back office.',
    ],
    publishSteps: [
      'Open PrestaShop back office → Catalog → Products.',
      'Edit the product.',
      'Paste optimized title, description, and meta tags.',
      'Save.',
    ],
  },
  {
    id: 'opencart',
    label: 'OpenCart',
    logoSlug: 'opencart',
    brandColor: '23A8DD',
    summary: 'Connect your OpenCart store to scan live product pages for SEO scoring.',
    urlPlaceholder: 'https://yourstore.com',
    urlHelp: 'Use your catalog storefront URL (not the /admin folder).',
    passwordHelp: 'Only if the catalog is behind maintenance mode with a visitor password.',
    supportsApiPush: false,
    supportsOAuth: false,
    docsUrl: 'https://docs.opencart.com/',
    connectSteps: [
      'Confirm products are enabled and visible on the storefront.',
      'Check that a sitemap extension or core sitemap is available.',
      'Copy your store homepage URL.',
      'Paste it below to run the SEO audit scan.',
      'Export optimized content and update products in OpenCart admin.',
    ],
    publishSteps: [
      'Open OpenCart admin → Catalog → Products.',
      'Edit the product.',
      'Update name, description, and meta title/description.',
      'Save.',
    ],
  },
  {
    id: 'square',
    label: 'Square Online',
    logoSlug: 'square',
    brandColor: '3E4348',
    summary: 'Connect your Square Online store to audit public product pages.',
    urlPlaceholder: 'https://yourstore.square.site',
    urlHelp: 'Use your Square Online site URL (*.square.site or connected custom domain).',
    passwordHelp: 'Rarely needed — only if the site is unpublished behind a preview lock.',
    supportsApiPush: false,
    supportsOAuth: false,
    docsUrl: 'https://squareup.com/help/us/en/article/6953-square-online-store',
    connectSteps: [
      'Publish your Square Online store and verify products are live.',
      'Copy your public store URL from the live site.',
      'Ensure product pages are linked from your homepage or sitemap.',
      'Paste the URL below — we scan discoverable product pages.',
      'Copy optimized content into Square Online item editor manually.',
    ],
    publishSteps: [
      'Open Square Dashboard → Items → Site library.',
      'Edit the item.',
      'Paste optimized title, description, and SEO text.',
      'Publish changes.',
    ],
  },
];

export const STORE_PLATFORM_BY_ID = Object.fromEntries(
  STORE_PLATFORMS.map((platform) => [platform.id, platform]),
);

export function getStorePlatform(platformId) {
  return STORE_PLATFORM_BY_ID[platformId] ?? null;
}

export const STORE_API_GUIDES = Object.fromEntries(
  STORE_PLATFORMS
    .filter((platform) => platform.apiFields?.length)
    .map((platform) => [
      platform.id,
      {
        id: platform.id,
        label: platform.label,
        docsUrl: platform.apiDocsUrl,
        summary: platform.apiSummary,
        steps: platform.apiSteps,
        fields: platform.apiFields,
        importSteps: platform.publishSteps,
      },
    ]),
);

export const MANUAL_PUBLISH_STEPS = [
  'Save your optimized product in AI Commerce Suite.',
  'Export the file for your platform or use Copy All.',
  'Open your store admin and edit the matching product.',
  'Paste the updated fields and save.',
];
