import LegalLayout from '../components/LegalLayout';

export default function TermsOfService() {
  return (
    <LegalLayout title="Terms of Service">
      <p>
        These Terms of Service (&quot;Terms&quot;) govern your use of AI Commerce Suite, operated by AI
        Ecommerce Solutions, available at{' '}
        <a href="https://ai-ecommerce-suite.netlify.app">ai-ecommerce-suite.netlify.app</a>. By creating an
        account or using the service, you agree to these Terms.
      </p>

      <h5>1. The Service</h5>
      <p>
        AI Commerce Suite is a software-as-a-service (SaaS) platform that provides AI-powered tools for
        eCommerce sellers, including product description generation, SEO tools, translations, image optimization,
        schema markup, and bulk export features.
      </p>

      <h5>2. Accounts</h5>
      <p>
        You must provide accurate information when registering. You are responsible for keeping your login
        credentials secure and for all activity under your account. Notify us immediately if you suspect
        unauthorized access.
      </p>

      <h5>3. Plans and Billing</h5>
      <p>We offer a Free plan and a paid Pro plan ($19/month):</p>
      <ul>
        <li>
          <strong>Free plan:</strong> limited daily AI generations and monthly saved products, as described on
          our Pricing page.
        </li>
        <li>
          <strong>Pro plan:</strong> unlimited AI generations and saved products, billed monthly as a
          subscription.
        </li>
      </ul>
      <p>
        Payments are processed by Lemon Squeezy. By subscribing, you also agree to Lemon Squeezy&apos;s terms.
        Subscriptions renew automatically each billing period unless cancelled before the renewal date. You can
        cancel anytime through your Lemon Squeezy customer portal or by contacting support.
      </p>

      <h5>4. Acceptable Use</h5>
      <p>You agree not to:</p>
      <ul>
        <li>Use the service for illegal, harmful, or fraudulent purposes</li>
        <li>Submit content that infringes intellectual property or privacy rights of others</li>
        <li>Attempt to bypass usage limits, scrape the platform, or abuse the API</li>
        <li>Reverse engineer, resell, or redistribute the service without permission</li>
        <li>Use automated systems to overload or disrupt the platform</li>
      </ul>
      <p>We may suspend or terminate accounts that violate these rules.</p>

      <h5>5. AI-Generated Content</h5>
      <p>
        Content generated by AI is provided &quot;as is&quot;. You are responsible for reviewing, editing, and
        verifying all output before using it in your store or marketing. We do not guarantee accuracy,
        completeness, SEO performance, or legal compliance of generated content.
      </p>

      <h5>6. Your Content</h5>
      <p>
        You retain ownership of the content you submit and the output generated for you. You grant us a limited
        license to process your content solely to provide and improve the service, including sending data to AI
        providers as described in our Privacy Policy.
      </p>

      <h5>7. Intellectual Property</h5>
      <p>
        AI Commerce Suite, including its design, code, branding, and features, is owned by us and protected by
        applicable laws. These Terms do not grant you any rights to our trademarks or software except the right
        to use the service as intended.
      </p>

      <h5>8. Availability and Changes</h5>
      <p>
        We aim to keep the service available but do not guarantee uninterrupted access. We may modify features,
        limits, or pricing with reasonable notice. Material changes to paid plans will be communicated in
        advance where required.
      </p>

      <h5>9. Disclaimer of Warranties</h5>
      <p>
        The service is provided &quot;as is&quot; and &quot;as available&quot; without warranties of any kind,
        whether express or implied, including merchantability, fitness for a particular purpose, and
        non-infringement.
      </p>

      <h5>10. Limitation of Liability</h5>
      <p>
        To the maximum extent permitted by law, we are not liable for indirect, incidental, special,
        consequential, or punitive damages, or for loss of profits, data, or business opportunities arising from
        your use of the service. Our total liability for any claim related to the service is limited to the
        amount you paid us in the 12 months before the claim.
      </p>

      <h5>11. Termination</h5>
      <p>
        You may stop using the service at any time. We may suspend or terminate your account if you breach these
        Terms or if required for legal or security reasons. Upon termination, your right to use the service ends.
        Provisions that should survive termination (including liability limits and intellectual property) will
        remain in effect.
      </p>

      <h5>12. Refunds</h5>
      <p>
        Subscription refunds are handled according to Lemon Squeezy&apos;s refund policy and applicable law. If
        you believe you were charged in error, contact us at{' '}
        <a href="mailto:stefanpanov0@gmail.com">stefanpanov0@gmail.com</a> within 14 days of the charge.
      </p>

      <h5>13. Governing Law</h5>
      <p>
        These Terms are governed by the laws of North Macedonia, without regard to conflict of law principles.
        Disputes will be resolved in the courts of North Macedonia, unless mandatory consumer protection laws in
        your country require otherwise.
      </p>

      <h5>14. Changes to These Terms</h5>
      <p>
        We may update these Terms from time to time. The updated version will be posted on this page. Continued
        use after changes constitutes acceptance of the new Terms.
      </p>

      <h5>15. Contact</h5>
      <p>
        Questions about these Terms? Contact us at{' '}
        <a href="mailto:stefanpanov0@gmail.com">stefanpanov0@gmail.com</a>.
      </p>
    </LegalLayout>
  );
}
